[project]
name = "openapi-generator-client"
version = "0.1.0"
license = "Apache-2.0"
requires-python = ">=3.11"
dependencies = ["openapi-client"]

[tool.uv.sources]
openapi-client = { path = "client" }
